# Generated by Django 4.2.1 on 2023-05-24 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('runtime', models.DecimalField(decimal_places=3, max_digits=10)),
                ('color', models.CharField(max_length=30)),
                ('wheel', models.CharField(choices=[('FRO', 'Передній'), ('BAC', 'Задній'), ('FUL', 'Повний')], max_length=3)),
                ('fuel', models.CharField(choices=[('PET', 'Бензин'), ('DIE', 'Дизель'), ('ELE', 'Електрика'), ('GAS', 'Газ'), ('HYB', 'Гібрид')], max_length=3)),
                ('accidents', models.CharField(choices=[('POS', 'Був у ДТП'), ('NEG', 'Не був у ДТП')], max_length=3)),
                ('brand', models.CharField(choices=[('OTH', 'Бензин'), ('BMW', 'BMW'), ('VOL', 'VolksWagen'), ('TOY', 'Toyota'), ('MIT', 'Mitsubishi'), ('SUB', 'Subaru'), ('FOR', 'Ford'), ('SKO', 'Skoda'), ('HUY', 'Huyndai'), ('CIT', 'Citroen')], max_length=3)),
                ('transmisson', models.CharField(choices=[('MEC', 'Механічна'), ('AUT', 'Автоматична')], max_length=3)),
                ('description', models.TextField(max_length=1000)),
                ('picture', models.ImageField(upload_to='car_pictures/')),
                ('create_time', models.TimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
