# Generated by Django 4.2.1 on 2023-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carseller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='transmisson',
            new_name='transmission',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('OTH', 'Інша'), ('BMW', 'BMW'), ('VOL', 'VolksWagen'), ('TOY', 'Toyota'), ('MIT', 'Mitsubishi'), ('SUB', 'Subaru'), ('FOR', 'Ford'), ('SKO', 'Skoda'), ('HUY', 'Huyndai'), ('CIT', 'Citroen')], max_length=3),
        ),
    ]
