# Generated by Django 4.2.1 on 2023-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_caruser_fav_cars_caruser_fav_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruser',
            name='cars_added',
            field=models.IntegerField(default=0),
        ),
    ]
